[workspace]
members = ["lb_predict_cn"]

[workspace.package]
version = "0.3.0"
authors = ["Simon Heath"]
description = "Utilities for working with whole genome sequencing data from liquid biopsy samples"
# documentation = "https://example.com/bar"

[profile.release]
lto = "thin"
debug = true

